var seachParams = {

    nid             :  ''       
  , sid             :  ''
  , cat             :  ''    
  , search          :  'macbook'    
  , zip             :  ''    
  , distance        :  ''    
  , min_price       :  ''    
  , max_price       :  ''    
  , type            :  ''    
  , category        :  ''    
  , subcat          :  ''    
  , sold            :  ''    
  , city            :  ''    
  , addisplay       :  ''    
  , sort            :  ''    
  , userid          :  ''    
  , markettype      :  ''    
  , adsstate        :  ''    
  , nocache         :  ''    
  , o_facetSelected :  ''    
  , o_facetKey      :  ''    
  , o_facetVal      :  ''    
  , viewSelect      :  ''    
  , viewNumResults  :  '50'    
  , sort            :  ''    
}

module.exports = seachParams